version: "3.9"

services:
  beacon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auraflux_beacon
    ports:
      - "5173:5173"
    # env_file:
    #   - ./docker-var.env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - auraflux_network

volumes:
  auraflux_data:

networks:
  auraflux_network:
    name: auraflux_network
    external: true
